/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
  aws_project_region: 'ap-southeast-1',
  aws_cognito_region: 'ap-southeast-1',
  aws_user_pools_id: 'ap-southeast-1_gx4p1WX52',
  aws_user_pools_web_client_id: '2cpvvk6voqbab726893t12rj2f',
  oauth: {},
}

export default awsmobile
